version: 2.1
jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: installing all deps
          command: |
            npm install
      - run:
          name: Run eslint
          command: |
            npm run test-lint
      - run:
          name: unit tests
          command: |
            npm run test-unit
      - run:
          name: run code-coverage
          command: |
            npm run test-coverage
            mkdir -p test-results/unit
            
      - store_test_results:
          path: test-results.xml
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            npm install    
      - run:
          name: create directory and zip
          command: |
            mkdir -p dist
            zip -r dist/dist.zip
      - store_artifacts:
          path: dist
          
workflows:
  build-and-packge:
    jobs:
      - ci-build
      - pack:
          filters:
            branches:
              only: master