version: 2.1
commands:
  install_deps:
    steps:
      - run:
        name: Install dependencies
        command: |
          npm install

jobs:
  ci-build:
    docker:
      -image: circleci/node:lts
      environment:
        NODE_ENV: test-output
    steps:
      - checkout
      - install_deps
      - run:
        name: unit tests
        command: |
         mkdir -p test-output
         npm run test-unit
          
workflows:
    build-and-packaging:
      jobs:
        - ci-build