version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: npm install
            

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment: 
      MOCHA_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout
      - run:
          name: running reporter
          command: |
            cd src
            npm install
      - run:
          name: Run eslint
          command: |
            npm run test-lint
      - run:
          name: unit tests
          command: |
            cd src
            npm run test-unit
      - run:
          name: run code-coverage
          command: |
            cd src
            npm run test-coverage
            mkdir -p test-results/unit
            mv test-results.xml testresults/unit/results.xml
            
      - store_test_results:
          path: src/test-results
  pack:
    docker:
      -image: circleci/nodelts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            cd src
            npm install    
      - run:
          name: create directory and zip
          command: |
            mkdir -p dist
            zip -r dist/src.zip src/
      - store_artifacts:
          path: dist
          
workflows:
  build-and-packge:
    jobs:
      - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master