version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: npm install
            

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment: 
      MOCHA_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout
      - install_deps
      - run:
          name: running reporter
          command: |
            cd src
            npm install mocha-junit-reporter
      - run:
          name: unit tests
          command: |
            cd src
            mkdir -p test-output
            npm run test-unit
      - run:
          name: Run eslint
          command: |
            npm run test-lint
      - run:
          name: run code-coverage
          command: |
            cd src
            npm run test-coverage
            mkdir -p test-results
            
      - store_test_results:
          path: test-output
  pack:
    docker:
      -image: circleci/nodelts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - run: |
          mkdir -p dist
          zip -r dist/dist.zip src/
      - store_artifacts:
          path: dist/dist.zip
          
workflows:
  build-and-packge:
    jobs:
      - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master