version: 2.1
jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: installing all deps
          command: |
            npm install
      - run:
          name: Run eslint
          command: |
            npm run test-lint
      - run:
          name: unit tests
          command: |
            npm run test-unit
      - run:
          name: run code-coverage
          command: |
            npm run test-coverage
            mkdir -p test-results/test-unit
            
      - store_test_results:
          path: test-results.xml

  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: servian
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: installing all deps and migrate
          command: |
            npm install
            node_modules/.bin/sequelize db:migrate
      - run:
          name: Run integration tests
          command: |
            npm run test-integration
            mkdir -p test-output/test-integration
      - store_test_output:
          path: test-output.xml
          
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            npm install    
      - run:
          name: create directory and zip
          command: |
            mkdir -p dist
            zip -r dist ./
      - store_artifacts:
          path: dist.zip
          
workflows:
  build-and-packge:
    jobs:
      - ci-build
      - integration-tests:
          requires:
            - ci-build
      - pack:
          filters:
            branches:
              only: master