version: 2.1
jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: installing all deps
          command: |
            npm install
      - run:
          name: Run eslint
          command: |
            npm run test-lint
      - run:
          name: unit tests
          command: |
            npm run test-unit
      - run:
          name: run code-coverage
          command: |
            npm run test-coverage
            
      - store_test_results:
          path: test-output

      - store_artifacts:
          path: test-output

  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: servian
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: installing all deps and migrate
          command: |
            npm install
            node_modules/.bin/sequelize db:migrate
      - run:
          name: Run integration tests
          command: |
            npm run test-integration
      - store_test_results:
          path: test-output
      - store_artifacts:
          path: test-output
          
  e2e:
    docker:
      - image: circleci/node:lts-browsers
        environment:
          QAW_HEADLESS: true
          QAW_ARTIFACT_PATH: tmp/artifacts
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: servian
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: installing deps
          command: |
            npm install
      - run:
          name: Run e2e
          command: npm run test-e2e

      - store_test_results:
          path: test-output
      - store_artifacts:
          path: test-output                
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            npm install    
      - run:
          name: create directory and zip
          command: |
            mkdir -p dist
            zip -r dist ./
      - store_artifacts:
          path: dist.zip
          
workflows:
  build-and-packge:
    jobs:
      - ci-build
      - integration-tests:
          requires:
            - ci-build
      - e2e:
          requires:
            - ci-build
            - integration-tests
      - pack:
          requires:
            - integration-tests
            - ci-build
            - e2e
          filters:
            branches:
              only:
                - master